# randomness
seed: 91
# data generator
generator:
  # bezier
  # options: "bezier_symmetric_double", "bezier_symmetric", "bezier_asymmetric"
  name: "bezier_symmetric_double"
  bounds: "saddle"  # options: pillow, dome, saddle
  num_uv: 10
  size: 10.0
  num_points: 4  # grid points
# fd simulation
fdm:
  load: -0.5  # -0.5, scale of vertical area load
# encoder
encoder: 
  hidden_layer_size: 256
  hidden_layer_num: 3
  activation_fn_name: "elu"
  final_activation_fn_name: "softplus"  # needs softplus to ensure positive output
# decoder
decoder:
  # If true, the decoder maps (z, boundary conditions) -> x. Otherwise, z -> x.
  include_params_xl: True
  hidden_layer_size: 256
  hidden_layer_num: 3
  activation_fn_name: "elu"
# loss function
loss:
  shape:
    include: True
    weight: 1.0  # weight of the shape error term in the loss function
    scale: 1.0  # 30.0, bbox length (used for normalization)
  residual:  # PINN term
    include: True
    weight: 1.0  # weight of the residual error term in the loss function
    scale: 1.0  # 0.5, fdm load scale (used for normalization)
# optimizer
optimizer:
  name: "adam"
  learning_rate: 5.0e-5  # 3.0e-5, Be careful with scientific notation in YAML!
# training
training:
  steps: 10000  # 10000
  batch_size: 64
