program: sweep.py
# method: random
method: grid
metric:
  goal: minimize
  name: train_loss_val
parameters:
  # generator parameters
  experiment_name:
    value: "saddle"
  num_uv: 
    value: 10
  # fd solver parameters
  fd_name:
    value: "shape_based_loads"  # constant, shape_based_loads
  pz:
    value: -0.5
  # encoder parameters
  hidden_layer_size:
    # values: [128, 256, 512]
    value: 256
  hidden_layer_num:
    # values: [3, 4, 5]
    value: 3
  activation_fn:
    value: "elu"
  final_activation_fn:
    value: "softplus"
  # optimizer parameters
  optimizer:
    value: "adam"
  learning_rate:
    values: [1e-3, 3e-3, 1e-4, 3e-4, 1e-5, 3e-5, 1e-6, 3e-6]    
  # training parameters
  steps:
    value: 10000
  batch_size:
    value: 64
  seed:
    value: 91