# randomness
seed: 91
# grid
grid:
  size: 10.0
  num_points: 4
  indices: [15, 13, 5, 7, 14, 12, 4, 6, 10, 8, 0, 2, 11, 9, 1, 3]
# data generator
generator:
  name: "saddle"  # "bezier_symmetric_double", "bezier_symmetric", "subd"
  num_uv: 10
# mechanical simulation
fdm:
  name: "area_loads"  # constant, area_loads
  load: -0.5  # scale of vertical load
# encoder
encoder: 
  hidden_layer_size: 256
  hidden_layer_num: 3
  activation_fn_name: "elu"
  final_activation_fn_name: "softplus"  # needs softplus to ensure positive output
# decoder
decoder:
  hidden_layer_size: 256
  hidden_layer_num: 3
  activation_fn_name: "elu"
loss:
  shape:
    include: True
    weight: 50.0
    scale: 30.0  # 30.0, bbox length
  residual:  # PINN term
    include: True
    weight: 1.0
    scale: 0.5  # 0.5, fdm load scale
# optimizer
optimizer:
  # for train.py
  name: "adam"
  learning_rate: 5.0e-5  # 3.0e-5, Be careful with scientific notation!
  # for train_coupled.py
  encoder:
    name: "adam"
    learning_rate: 5.0e-5  # 3.0e-5, Be careful with scientific notation!
  decoder:
    name: "adam"
    learning_rate: 5.0e-5  # 5.0e-5
# training
training:
  steps: 10000  # 10000
  batch_size: 64
