program: sweep_coupled.py
method: random
metric:
  goal: minimize
  name: piggyback_train_loss_val
parameters:
  # generator parameters
  experiment_name:
    value: "saddle"  # pillow, dome, saddle
  num_uv: 
    value: 10
  # fd solver parameters
  fd_name:
    value: "shape_based_loads"  # constant, shape_based_loads
  pz:
    value: -0.5
  # encoder parameters
  encoder_hidden_layer_size:
    value: 256
  encoder_hidden_layer_num:
    value: 3
  encoder_activation_fn:
    value: "elu"
  encoder_final_activation_fn:
    value: "softplus"
  # piggyback optimizer parameters  
  encoder_learning_rate:
    value: 0.00003
  # piggyback decoder parameters
  hidden_layer_size:
    values: [128, 256, 512]
  hidden_layer_num:
    values: [3, 4, 5]
  activation_fn:
    value: "elu"  
  # piggyback optimizer parameters
  learning_rate:
    values: [1e-4, 3e-4, 1e-5, 3e-5, 1e-6, 3e-6]    
  # training parameters
  optimizer:
    value: "adam"
  steps:
    value: 10000
  batch_size:
    value: 64
  seed:
    value: 91